// frontend/src/components/CompanyAvatar.tsx
import clsx from "clsx";

const COLORS = [
  "bg-brand-100 text-brand-700",
  "bg-emerald-100 text-emerald-700",
  "bg-amber-100 text-amber-700",
  "bg-rose-100 text-rose-700",
  "bg-violet-100 text-violet-700",
  "bg-cyan-100 text-cyan-700",
];

function hashName(name: string): number {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = ((h << 5) - h + name.charCodeAt(i)) | 0;
  return Math.abs(h);
}

interface Props {
  name: string;
  size?: "sm" | "md" | "lg";
}

const SIZES = {
  sm: "w-8 h-8 text-xs",
  md: "w-10 h-10 text-sm",
  lg: "w-14 h-14 text-lg",
};

export function CompanyAvatar({ name, size = "md" }: Props) {
  const initials = name
    .split(/[\s-]+/)
    .slice(0, 2)
    .map((w) => w[0])
    .join("")
    .toUpperCase();
  const colorClass = COLORS[hashName(name) % COLORS.length];

  return (
    <div
      className={clsx(
        "rounded-xl font-semibold flex items-center justify-center shrink-0",
        SIZES[size],
        colorClass
      )}
    >
      {initials}
    </div>
  );
}

// src/lib/components/ui/CompanyAvatar.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn.js';

	interface Props {
		name: string;
		size?: 'sm' | 'md' | 'lg';
		class?: string;
	}

	let { name, size = 'md', class: className }: Props = $props();

	const palette = [
		'bg-blue-600',
		'bg-emerald-600',
		'bg-violet-600',
		'bg-amber-600',
		'bg-rose-600',
		'bg-cyan-600',
		'bg-indigo-600',
		'bg-teal-600'
	];

	function hashName(str: string): number {
		let hash = 0;
		for (let i = 0; i < str.length; i++) {
			hash = ((hash << 5) - hash + str.charCodeAt(i)) | 0;
		}
		return Math.abs(hash);
	}

	let letter = $derived(name.trim().charAt(0).toUpperCase());
	let colorClass = $derived(palette[hashName(name) % palette.length]);

	const sizes = {
		sm: 'h-10 w-10 text-sm',
		md: 'h-12 w-12 text-base',
		lg: 'h-14 w-14 text-xl'
	};
</script>

<div
	class={cn(
		'inline-flex items-center justify-center rounded-xl font-bold text-white shrink-0',
		colorClass,
		sizes[size],
		className
	)}
	aria-hidden="true"
>
	{letter}
</div>
